import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { HeaderLayout } from '@/layout/header';
import { FooterLayout } from '@/layout/footer';
import { AuthProvider } from '@/context/auth.context';
import Provider from '@/provider/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Provider>
      <html lang="en">
        <body className={inter.className}>
          <AuthProvider>
            <HeaderLayout />
            {children}
            <FooterLayout />
          </AuthProvider>
        </body>
      </html>
    </Provider>
  );
}
